language: node_js
node_js:
  - 12
before_install:
- openssl aes-256-cbc -K $encrypted_3fd6b7ca532d_key -iv $encrypted_3fd6b7ca532d_iv
  -in vivid-spot-341421-e424def25b01.json.enc -out vivid-spot-341421-e424def25b01.json
  -d
install:
# Set the correct project to deploy to
- gcloud config set project vivid-spot-341421
script:
- npm run test
deploy:
  provider: gae
  keyfile: vivid-spot-341421-e424def25b01.json
  project: vue-tutorial